apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-controller
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sample-controller
rules:
  - apiGroups:
    - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
     - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
  - apiGroups:
    - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
    - samplecontroller.k8s.io
    resources:
      - vms
      - vms/status
    verbs:
      - list
      - watch
      - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sample-controller
subjects:
  - kind: ServiceAccount
    name: sample-controller
    namespace: default
roleRef:
  kind: ClusterRole
  name: sample-controller
  apiGroup: rbac.authorization.k8s.io
